version: "2"
linters:
  enable:
    - asasalint
    - bodyclose
    - canonicalheader
    - copyloopvar
    - durationcheck
    - embeddedstructfieldcheck
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gosec
    - mirror
    - perfsprint
    - protogetter
    - prealloc
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wsl_v5

  settings:
    errchkjson:
      check-error-free-encoding: true
    errorlint:
      errorf: false
    testifylint:
      disable:
        - require-error
    revive:
      rules:
        - name: redefines-builtin-id
          disabled: true
    perfsprint:
      error-format: false
    staticcheck:
      checks: ["all", "-QF1008"]

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
